### ISSUE TITLE
directive @contact not generated leading to invalid schema when @ContactDirective is used

### ISSUE THREAD

**Issue by chriskn** [ExpediaGroup/graphql-kotlin#1510]
**Library Version**
6.1.0 with spring-boot 2.7.2 

application.yml

```
graphql:
  packages: 'my.package'
  federation:
    enabled: true
    tracing:
      enabled: true
    opt-in-v2: true
```

**Describe the bug**
When using the @ContactDirective annotation like this

```
@ContactDirective(
    name = "My Team",
    url = "foo",
    description = "bar"
)
@Component
class MySchema : Schema
```

I get the @contact generated for the schema, which is fine

```
schema @contact(description : "bar", name : "My Team", url : "foo"){
  query: Query
}
```

but what's **missing** is the definition of the @contact directive:

```
directive @contact(
    "Contact title of the subgraph owner"
    name: String!
    "URL where the subgraph's owner can be reached"
    url: String
    "Other relevant notes can be included here; supports markdown links"
    description: String
) on SCHEMA
```

**To Reproduce**
Use the annotation and generate sdl

**Expected behavior**
`directive @contact` is generated and part of sdl
