### ISSUE TITLE
Federation key directive throwing TypeNotSupportedException

### ISSUE THREAD

**Issue by DevYukine** [ExpediaGroup/graphql-kotlin#827]
**Library Version**
3.6.0

**Describe the bug**
When using the Key directive (like shown [here](https://github.com/ExpediaGroup/graphql-kotlin/tree/master/graphql-kotlin-federation)) i get the following exception:

```
com.expediagroup.graphql.exceptions.TypeNotSupportedException: Cannot convert com.expediagroup.graphql.federation.directives.FieldSet since it is not a valid GraphQL type or outside the supported packages "[com.example.graphqlcore.model]"
```

**To Reproduce**
I'm using `com.expediagroup:graphql-kotlin-spring-server` version 3.6.0

my application.yml
```yml
spring:
  exposed:
    generate-ddl: true
  datasource:
    url: "jdbc:h2:mem:test"
    driver-class-name: "org.h2.Driver"
    username: "root"
    password: ""

graphql:
  packages:
    - "com.example.graphqlcore.model"
  introspection:
    enabled: true
  federation:
    enabled: true
  playground:
    enabled: true
```

i have a custom schema generator hook for custom types with federation, don't think its related but too make sure i will add it in here

```kotlin
@Component
class CustomSchemaGeneratorHooks : FederatedSchemaGeneratorHooks(FederatedTypeRegistry(emptyMap())) {
    override fun willGenerateGraphQLType(type: KType): GraphQLType? = when (type.classifier as? KClass<*>) {
        LocalDateTime::class -> ExtendedScalars.DateTime
        Long::class -> ExtendedScalars.GraphQLLong
        else -> null
    }
}
```

and now when i add the key directive to any class im receiving the exception, im showing this example class here

```kotlin
@GraphQLName("User")
@KeyDirective(fields = FieldSet("id"))
data class GraphQLUser(
        @Id
        @GraphQLDescription("The id of the user")
        val id: Long
)
```

**Expected behavior**
adding the key directive to the schema and not getting this exception

**Comment by smyrick** [comment]
@DevYukine What happens if you set the packages to include the generator types?

```yml
graphql:
  packages:
    - "com.example.graphqlcore.model"
    - "com.expediagroup.graphql.federation"
```
